"""empty message

Revision ID: cf223f82a25d
Revises: d5f28a853ba6
Create Date: 2025-05-08 16:33:16.080088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf223f82a25d'
down_revision = 'd5f28a853ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estuches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lapiceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('estuche_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estuche_id'], ['estuches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lapiceros')
    op.drop_table('estuches')
    # ### end Alembic commands ###
